# Home page
adminHomePage:
    path:     /rz-admin
    defaults: { _controller: Themes\Rozier\RozierApp::indexAction }
adminHomePageSlash:
    path:     /rz-admin/
    defaults: { _controller: Themes\Rozier\RozierApp::indexAction }

loginPage:
    path:     /login
    defaults: { _controller: Themes\Rozier\Controllers\LoginController::indexAction }
logoutPage:
    path:     /rz-admin/logout
    defaults: { _controller: Themes\Rozier\Controllers\LoginController::logoutAction }
loginFailedPage:
    path:     /login_failed
    defaults: { _controller: Themes\Rozier\Controllers\LoginController::indexAction }
loginCheckPage:
    path:     /rz-admin/login_check
    defaults: { _controller: Themes\Rozier\Controllers\LoginController::checkAction }

# CACHES
deleteDoctrineCache:
    path:     /rz-admin/cache/delete-doctrine-cache
    defaults: { _controller: Themes\Rozier\Controllers\CacheController::deleteDoctrineCache }

#  NODES
nodesHomePage:
    path:     /rz-admin/nodes
    defaults: { _controller: Themes\Rozier\Controllers\NodesController::indexAction }
nodesEditPage:
    path:     /rz-admin/nodes/edit/{node_id}
    defaults: { _controller: Themes\Rozier\Controllers\NodesController::editAction }
    requirements: { node_id : "[0-9]+" }
nodesEditSourcePage:
    path:     /rz-admin/nodes/edit/{node_id}/source/{translation_id}
    defaults: { _controller: Themes\Rozier\Controllers\NodesController::editSourceAction }
    requirements: { node_id : "[0-9]+", translation_id : "[0-9]+" }
nodesEditTagsPage:
    path:     /rz-admin/nodes/edit/{node_id}/tags
    defaults: { _controller: Themes\Rozier\Controllers\NodesController::editTagsAction }
    requirements: { node_id : "[0-9]+" }
nodesRemoveTagsPage:
    path:     /rz-admin/nodes/edit/{node_id}/tags/{tag_id}/remove
    defaults: { _controller: Themes\Rozier\Controllers\NodesController::removeTagAction }
    requirements: { node_id : "[0-9]+", tag_id : "[0-9]+" }
nodesEditAliasesPage:
    path:     /rz-admin/nodes/edit/{node_id}/aliases
    defaults: { _controller: Themes\Rozier\Controllers\UrlAliasesController::editAliasesAction }
    requirements: { node_id : "[0-9]+" }
nodesTreePage:
    path:     /rz-admin/nodes/tree/{node_id}
    defaults: { _controller: Themes\Rozier\Controllers\NodesController::treeAction }
    requirements: { node_id : "[0-9]+" }
nodesAddPage:
    path:     /rz-admin/nodes/add/{node_type_id}/{translation_id}
    defaults: { _controller: Themes\Rozier\Controllers\NodesController::addAction }
    requirements: { node_type_id : "[0-9]+", translation_id : "[0-9]+" }
nodesAddChildPage:
    path:     /rz-admin/nodes/add-child/{node_id}
    defaults: { _controller: Themes\Rozier\Controllers\NodesController::addChildAction }
    requirements: { node_id : "[0-9]+" }
nodesDeletePage:
    path:     /rz-admin/nodes/delete/{node_id}
    defaults: { _controller: Themes\Rozier\Controllers\NodesController::deleteAction }
    requirements: { node_id : "[0-9]+" }

## Ajax
nodeAjaxEdit:
    path:     /rz-admin/ajax/node/edit/{node_id}
    defaults: { _controller: Themes\Rozier\AjaxControllers\AjaxNodesController::editAction }
    requirements: { node_id : "[0-9]+" }

# Node TYPES
nodeTypesHomePage:
    path:     /rz-admin/node-types
    defaults: { _controller: Themes\Rozier\Controllers\NodeTypesController::indexAction }
nodeTypesEditPage:
    path:     /rz-admin/node-types/edit/{node_type_id}
    defaults: { _controller: Themes\Rozier\Controllers\NodeTypesController::editAction }
    requirements: { node_type_id : "[0-9]+" }
nodeTypesAddPage:
    path:     /rz-admin/node-types/add
    defaults: { _controller: Themes\Rozier\Controllers\NodeTypesController::addAction }
nodeTypesDeletePage:
    path:     /rz-admin/node-types/delete/{node_type_id}
    defaults: { _controller: Themes\Rozier\Controllers\NodeTypesController::deleteAction }
    requirements: { node_type_id : "[0-9]+" }
nodeTypesSchemaUpdate:
    path:     /rz-admin/node-types/update-schema/{_token}
    defaults: { _controller: Themes\Rozier\Controllers\SchemaController::updateNodeTypesSchemaAction }
    requirements: { _token : "[A-z0-9\-\_\$]+" }

# Node type FIELDS
nodeTypeFieldsListPage:
    path:     /rz-admin/node-types/fields/{node_type_id}
    defaults: { _controller: Themes\Rozier\Controllers\NodeTypeFieldsController::listAction }
    requirements: { node_type_id : "[0-9]+" }
nodeTypeFieldsEditPage:
    path:     /rz-admin/node-types/fields/edit/{node_type_field_id}
    defaults: { _controller: Themes\Rozier\Controllers\NodeTypeFieldsController::editAction }
    requirements: { node_type_field_id : "[0-9]+" }
nodeTypeFieldsAddPage:
    path:     /rz-admin/node-types/fields/add/{node_type_id}
    defaults: { _controller: Themes\Rozier\Controllers\NodeTypeFieldsController::addAction }
    requirements: { node_type_id : "[0-9]+" }
nodeTypeFieldsDeletePage:
    path:     /rz-admin/node-types/fields/delete/{node_type_field_id}
    defaults: { _controller: Themes\Rozier\Controllers\NodeTypeFieldsController::deleteAction }
    requirements: { node_type_field_id : "[0-9]+" }
nodeTypesFieldSchemaUpdate:
    path:     /rz-admin/node-types/fields/update-schema/{node_type_id}/{_token}
    defaults: { _controller: Themes\Rozier\Controllers\SchemaController::updateNodeTypeFieldsSchemaAction }
    requirements: { node_type_id : "[0-9]+", _token: "[A-z0-9\-\_\$]+" }

# SETTINGS
settingsHomePage:
    path:     /rz-admin/settings
    defaults: { _controller: Themes\Rozier\Controllers\SettingsController::indexAction }
settingsEditPage:
    path:     /rz-admin/settings/edit/{setting_id}
    defaults: { _controller: Themes\Rozier\Controllers\SettingsController::editAction }
    requirements: { setting_id : "[0-9]+" }
settingsAddPage:
    path:     /rz-admin/settings/add
    defaults: { _controller: Themes\Rozier\Controllers\SettingsController::addAction }
settingsDeletePage:
    path:     /rz-admin/settings/delete/{setting_id}
    defaults: { _controller: Themes\Rozier\Controllers\SettingsController::deleteAction }
    requirements: { setting_id : "[0-9]+" }

# TAGS
tagsHomePage:
    path:     /rz-admin/tags
    defaults: { _controller: Themes\Rozier\Controllers\TagsController::indexAction }
tagsEditPage:
    path:     /rz-admin/tags/edit/{tag_id}
    defaults: { _controller: Themes\Rozier\Controllers\TagsController::editAction }
    requirements: { tag_id : "[0-9]+" }
tagsAddPage:
    path:     /rz-admin/tags/add
    defaults: { _controller: Themes\Rozier\Controllers\TagsController::addAction }
tagsDeletePage:
    path:     /rz-admin/tags/delete/{tag_id}
    defaults: { _controller: Themes\Rozier\Controllers\TagsController::deleteAction }
    requirements: { tag_id : "[0-9]+" }
## Ajax
tagAjaxEdit:
    path:     /rz-admin/ajax/tag/edit/{tag_id}
    defaults: { _controller: Themes\Rozier\AjaxControllers\AjaxTagsController::editAction }
    requirements: { tag_id : "[0-9]+" }

# USERS
usersHomePage:
    path:     /rz-admin/users
    defaults: { _controller: Themes\Rozier\Controllers\UsersController::indexAction }
usersEditPage:
    path:     /rz-admin/users/edit/{user_id}
    defaults: { _controller: Themes\Rozier\Controllers\UsersController::editAction }
    requirements: { user_id : "[0-9]+" }
usersEditRolesPage:
    path:     /rz-admin/users/edit/{user_id}/roles
    defaults: { _controller: Themes\Rozier\Controllers\UsersController::editRolesAction }
    requirements: { user_id : "[0-9]+" }
usersRemoveRolesPage:
    path:     /rz-admin/users/edit/{user_id}/role/{role_id}/remove
    defaults: { _controller: Themes\Rozier\Controllers\UsersController::removeRoleAction }
    requirements: { user_id : "[0-9]+", role_id : "[0-9]+" }
usersAddPage:
    path:     /rz-admin/users/add
    defaults: { _controller: Themes\Rozier\Controllers\UsersController::addAction }
usersDeletePage:
    path:     /rz-admin/users/delete/{user_id}
    defaults: { _controller: Themes\Rozier\Controllers\UsersController::deleteAction }
    requirements: { user_id : "[0-9]+" }

# TRANSLATIONS
translationsHomePage:
    path:     /rz-admin/translations
    defaults: { _controller: Themes\Rozier\Controllers\TranslationsController::indexAction }
translationsEditPage:
    path:     /rz-admin/translations/edit/{translation_id}
    defaults: { _controller: Themes\Rozier\Controllers\TranslationsController::editAction }
    requirements: { translation_id : "[0-9]+" }
translationsSetDefaultPage:
    path:     /rz-admin/translations/set-default/{translation_id}
    defaults: { _controller: Themes\Rozier\Controllers\TranslationsController::setDefaultAction }
    requirements: { translation_id : "[0-9]+" }
translationsAddPage:
    path:     /rz-admin/translations/add
    defaults: { _controller: Themes\Rozier\Controllers\TranslationsController::addAction }
translationsDeletePage:
    path:     /rz-admin/translations/delete/{translation_id}
    defaults: { _controller: Themes\Rozier\Controllers\TranslationsController::deleteAction }
    requirements: { translation_id : "[0-9]+" }

# DOCUMENTS
documentsHomePage:
    path:     /rz-admin/documents
    defaults: { _controller: Themes\Rozier\Controllers\DocumentsController::indexAction }
documentsEditPage:
    path:     /rz-admin/documents/edit/{document_id}
    defaults: { _controller: Themes\Rozier\Controllers\DocumentsController::editAction }
    requirements: { document_id : "[0-9]+" }
documentsUploadPage:
    path:     /rz-admin/documents/upload
    defaults: { _controller: Themes\Rozier\Controllers\DocumentsController::uploadAction }
documentsDeletePage:
    path:     /rz-admin/documents/delete/{document_id}
    defaults: { _controller: Themes\Rozier\Controllers\DocumentsController::deleteAction }
    requirements: { document_id : "[0-9]+" }
# Ajax
documentsAjaxExplorerPage:
    path:     /rz-admin/ajax/documents/explore
    defaults: { _controller: Themes\Rozier\AjaxControllers\AjaxDocumentsExplorerController::indexAction }

# THEMES
themesHomePage:
    path:     /rz-admin/themes
    defaults: { _controller: Themes\Rozier\Controllers\ThemesController::indexAction }
themesEditPage:
    path:     /rz-admin/themes/edit/{theme_id}
    defaults: { _controller: Themes\Rozier\Controllers\ThemesController::editAction }
    requirements: { theme_id : "[0-9]+" }
themesAddPage:
    path:     /rz-admin/themes/add
    defaults: { _controller: Themes\Rozier\Controllers\ThemesController::addAction }
themesDeletePage:
    path:     /rz-admin/themes/delete/{theme_id}
    defaults: { _controller: Themes\Rozier\Controllers\ThemesController::deleteAction }
    requirements: { theme_id : "[0-9]+" }

# ROLES
rolesHomePage:
    path:     /rz-admin/roles
    defaults: { _controller: Themes\Rozier\Controllers\RolesController::indexAction }
rolesEditPage:
    path:     /rz-admin/roles/edit/{role_id}
    defaults: { _controller: Themes\Rozier\Controllers\RolesController::editAction }
    requirements: { role_id : "[0-9]+" }
rolesAddPage:
    path:     /rz-admin/roles/add
    defaults: { _controller: Themes\Rozier\Controllers\RolesController::addAction }
rolesDeletePage:
    path:     /rz-admin/roles/delete/{role_id}
    defaults: { _controller: Themes\Rozier\Controllers\RolesController::deleteAction }
    requirements: { role_id : "[0-9]+" }

# GROUPS
groupsHomePage:
    path:     /rz-admin/groups
    defaults: { _controller: Themes\Rozier\Controllers\GroupsController::indexAction }
groupsEditPage:
    path:     /rz-admin/groups/edit/{group_id}
    defaults: { _controller: Themes\Rozier\Controllers\GroupsController::editAction }
    requirements: { group_id : "[0-9]+" }
groupsEditRolesPage:
    path:     /rz-admin/groups/edit/{group_id}/roles
    defaults: { _controller: Themes\Rozier\Controllers\GroupsController::editRolesAction }
    requirements: { group_id : "[0-9]+" }
groupsRemoveRolesPage:
    path:     /rz-admin/groups/edit/{group_id}/roles/{role_id}/remove
    defaults: { _controller: Themes\Rozier\Controllers\GroupsController::removeRolesAction }
    requirements: { group_id : "[0-9]+", role_id : "[0-9]+" }
groupsAddPage:
    path:     /rz-admin/groups/add
    defaults: { _controller: Themes\Rozier\Controllers\GroupsController::addAction }
groupsDeletePage:
    path:     /rz-admin/groups/delete/{group_id}
    defaults: { _controller: Themes\Rozier\Controllers\GroupsController::deleteAction }
    requirements: { group_id : "[0-9]+" }
