##
# Always use plural entities' name
##
rozierRemoveTrailingSlash:
    path: /{url}
    defaults:
        _controller: Themes\Rozier\RozierApp::removeTrailingSlashAction
    requirements:
        url: .*/$
    methods: [GET]

# Home page
adminHomePage:
    path:     /rz-admin
    defaults:
        _controller: Themes\Rozier\Controllers\DashboardController::indexAction
loginRoutes:
    prefix: /rz-admin
    resource: "routing/login.yml"

ajaxSessionMessages:
    path:     /rz-admin/session/messages
    methods: [GET]
    defaults:
        _controller: Themes\Rozier\AjaxControllers\AjaxSessionMessages::getMessagesAction

#Ping
ping:
    path:     /rz-admin/ping
    methods: [GET]
    defaults:
        _controller: Themes\Rozier\Controllers\PingController::indexAction

# CACHES
deleteDoctrineCache:
    path:     /rz-admin/cache/delete-doctrine-cache
    defaults:
        _controller: Themes\Rozier\Controllers\CacheController::deleteDoctrineCache
deleteAssetsCache:
    path:     /rz-admin/cache/delete-assets-cache
    defaults:
        _controller: Themes\Rozier\Controllers\CacheController::deleteAssetsCache

# NODES
nodesHomePage:
    path:     /rz-admin/nodes
    defaults:
        _controller: Themes\Rozier\Controllers\Nodes\NodesController::indexAction
nodesRoutes:
    resource: "routing/nodes.yml"
    prefix: /rz-admin/nodes

## Ajax
ajaxRequestsRoutes:
    resource: "routing/ajax.yml"
    prefix: /rz-admin/ajax

# Node TYPES
nodeTypesHomePage:
    path:     /rz-admin/node-types
    defaults:
        _controller: Themes\Rozier\Controllers\NodeTypes\NodeTypesController::indexAction
nodeTypesRoutes:
    resource: "routing/node-types.yml"
    prefix: /rz-admin/node-types

# Node type FIELDS
nodeTypeFieldsRoutes:
    resource: "routing/node-type-fields.yml"
    prefix: /rz-admin/node-types/fields


# SETTINGS
settingsHomePage:
    path:     /rz-admin/settings
    defaults:
        _controller: Themes\Rozier\Controllers\SettingsController::indexAction
settingsRoutes:
    resource: "routing/settings.yml"
    prefix: /rz-admin/settings


# SETTINGS GROUPS
settingGroupsHomePage:
    path:     /rz-admin/setting-groups
    defaults:
        _controller: Themes\Rozier\Controllers\SettingGroupsController::indexAction
settingGroupsRoutes:
    resource: "routing/setting-groups.yml"
    prefix: /rz-admin/setting-groups


# TAGS
tagsHomePage:
    path:     /rz-admin/tags
    defaults:
        _controller: Themes\Rozier\Controllers\Tags\TagsController::indexAction
tagsRoutes:
    resource: "routing/tags.yml"
    prefix: /rz-admin/tags

# USERS
usersHomePage:
    path:     /rz-admin/users
    defaults:
        _controller: Themes\Rozier\Controllers\Users\UsersController::indexAction
usersRoutes:
    resource: "routing/users.yml"
    prefix: /rz-admin/users

# ATTRIBUTES
attributesHomePage:
    path:     /rz-admin/attributes
    defaults:
        _controller: Themes\Rozier\Controllers\Attributes\AttributeController::defaultAction
attributesRoutes:
    resource: "routing/attributes.yml"
    prefix: /rz-admin/attributes

# FONTS
fontsHomePage:
    path:     /rz-admin/fonts
    defaults:
        _controller: Themes\Rozier\Controllers\FontsController::defaultAction
fontsRoutes:
    resource: "routing/fonts.yml"
    prefix: /rz-admin/fonts


# FOLDERS
foldersHomePage:
    path:     /rz-admin/folders
    defaults:
        _controller: Themes\Rozier\Controllers\FoldersController::indexAction
foldersRoutes:
    resource: "routing/folders.yml"
    prefix: /rz-admin/folders


# TRANSLATIONS
translationsHomePage:
    path:     /rz-admin/translations
    defaults:
        _controller: Themes\Rozier\Controllers\TranslationsController::indexAction
translationsRoutes:
    resource: "routing/translations.yml"
    prefix: /rz-admin/translations


# DOCUMENTS
documentsHomePage:
    path:     /rz-admin/documents/{folderId}
    defaults:
        _controller: Themes\Rozier\Controllers\Documents\DocumentsController::indexAction
        folderId: null
    requirements: { folderId : "[0-9]+" }
documentsRoutes:
    resource: "routing/documents.yml"
    prefix: /rz-admin/documents


# DOCUMENTS
redirectionsHomePage:
    path:     /rz-admin/redirections
    defaults:
        _controller: Themes\Rozier\Controllers\RedirectionsController::defaultAction
redirectionsRoutes:
    resource: "routing/redirections.yml"
    prefix: /rz-admin/redirections

# THEMES
themesRoutes:
    resource: "routing/themes.yml"
    prefix: /rz-admin/themes


# ROLES
rolesHomePage:
    path:     /rz-admin/roles
    defaults:
        _controller: Themes\Rozier\Controllers\RolesController::defaultAction
rolesRoutes:
    resource: "routing/roles.yml"
    prefix: /rz-admin/roles


# GROUPS
groupsHomePage:
    path:     /rz-admin/groups
    defaults:
        _controller: Themes\Rozier\Controllers\GroupsController::defaultAction
groupsRoutes:
    resource: "routing/groups.yml"
    prefix: /rz-admin/groups


#LOGS
historyHomePage:
    path:     /rz-admin/history
    defaults:
        _controller: Themes\Rozier\Controllers\HistoryController::indexAction
historyUserPage:
    path:     /rz-admin/history/user/{userId}
    requirements: { userId : "[0-9]+" }
    defaults:
        _controller: Themes\Rozier\Controllers\HistoryController::userAction

# Custom Form
customFormsHomePage:
    path:     /rz-admin/custom-forms
    defaults:
        _controller: Themes\Rozier\Controllers\CustomForms\CustomFormsController::defaultAction
customFormsRoutes:
    resource: "routing/custom-forms.yml"
    prefix: /rz-admin/custom-forms

# Custom Form Answer
customFormAnswersRoutes:
    resource: "routing/custom-form-answers.yml"
    prefix: /rz-admin/custom-form-answers

# Custom Form FIELDS
customFormFieldsRoutes:
    resource: "routing/custom-forms-fields.yml"
    prefix: /rz-admin/custom-forms/fields


# SEARCH
searchNodePage:
    path:     /rz-admin/search
    defaults:
        _controller: Themes\Rozier\Controllers\SearchController::searchNodeAction
searchNodeSourcePage:
    path:     /rz-admin/search/{nodetypeId}
    defaults:
        _controller: Themes\Rozier\Controllers\SearchController::searchNodeSourceAction
    requirements: { nodetypeId : "[0-9]+" }

aboutPage:
    path: /rz-admin/about
    defaults:
        _controller: Themes\Rozier\Controllers\AboutController::indexAction


#
# CSS to style with main color
# NOT SECURED ROUTES
#
cssMainColor:
    path : /css/main-color.css
    defaults:
        _controller: Themes\Rozier\RozierApp::cssAction

loginImagePage:
    path: /css/login/image
    defaults:
        _controller: Themes\Rozier\Controllers\LoginController::imageAction

