---
name: "Default theme"
author: "Ambroise Maupate"
copyright: "Ambroise Maupate - Julien Blanchet"
themeDir: "DefaultTheme"
supportedLocale:
    - en
    - fr
    - ru
    - tr
versionRequire: "1.1.0"
importFiles:
    roles: []
    groups: []
    settings: []
    nodetypes:
        - Resources/import/nodetype/BasicBlock.rzt
        - Resources/import/nodetype/BasicNewsletter.rzt
        - Resources/import/nodetype/Link.rzt
        - Resources/import/nodetype/Neutral.rzt
        - Resources/import/nodetype/Page.rzt
    tags: []
    nodes:
        - "Resources/import/node/node-main-menu.rzn"
