---
name: "Default theme"
author: "Ambroise Maupate"
copyright: "Ambroise Maupate and Julien Blanchet"
themeDir: "DefaultTheme"
supportedLocale:
    - en
    - fr
    - ru
versionRequire: "0.13.2"
importFiles:
    roles: []
    groups: []
    settings: []
    nodetypes:
        - "Resources/import/nodetype/Page.rzt"
        - "Resources/import/nodetype/Neutral.rzt"
        - "Resources/import/nodetype/BasicBlock.rzt"
    tags: []
    nodes:
        - "Resources/import/node/node-home.rzn"
