---
name: "Default theme"
author: "Ambroise Maupate"
copyright: "Ambroise Maupate - Julien Blanchet"
themeDir: "DefaultTheme"
supportedLocale:
    - en
    - fr
    - ru
    - tr
versionRequire: "1.7.0"
importFiles:
    roles: []
    groups: []
    settings: []
    attributes:
        - Resources/import/attributes.json
    nodetypes:
        - Resources/import/nodetype/BasicBlock.json
        - Resources/import/nodetype/Link.json
        - Resources/import/nodetype/Neutral.json
        - Resources/import/nodetype/Page.json
    tags:
        - Resources/import/tags.json
    nodes:
        - "Resources/import/node/node-main-menu.rzn"
