---
name: "Install theme"
author: "Ambroise Maupate"
copyright: "Ambroise Maupate and Julien Blanchet"
themeDir: "Install"
supportedLocale:
    - "en"
    - "fr"
versionRequire: "0.6.0"
importFiles:
    roles:
        - "Resources/import/roles.rzt"
    groups:
        - "Resources/import/groups.rzt"
    settings:
        - "Resources/import/settings.rzt"
    nodetypes: []
